<?php

/*
 * Implements hook_ENTITY_TYPE_update()
 */
function content_bean_cards_block_content_update(Drupal\Core\Entity\EntityInterface $entity){
	// Clear cache if BlockContent is of type 'content_card'
	if ($entity->bundle() == 'content_card') {
	  \Drupal::service('cache.render')->invalidateAll();
	}
}

function content_bean_cards_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }
}

function content_bean_cards_preprocess_block(&$variables)
{
  // Include the css file when the block is used
  if ($vars['plugin_id'] == 'social_media_red_bar') {
    $variables['#attached']['library'][] = 'content_card/content_card';
    $variables['attributes']['class'][] = 'content_card';
  }
}