<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function display_county_jobs_preprocess_html(&$variables)
{
  // Include the program_offering_blocks css file for the block
//  if (substr($variables['plugin_id'], 0, 23) == 'display_county_jobs') {
    $variables['#attached']['library'][] = 'display_county_jobs/display_county_jobs';
 //   $variables['attributes']['class'][] = 'display_county_jobs';
  //}
}
