<?php

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_entity_presave().
 */
function educational_programs_field_node_presave($entity)
{
  $program_name = '';

  foreach ($entity->getFields() as $field) {
    if ($field->getFieldDefinition()->getType() == 'educational_programs_field') {
      if (!empty($entity->get($field->getName())[0])) {
        $program_name =  Term::load($entity->get($field->getName())[0]->get('term_id')->getValue())->getName();
        break;
      }
    }
  }

  if (!empty($program_name)) {
    $entity->setTitle($program_name);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function educational_programs_field_preprocess_node(&$variables)
{
  $variables['#attached']['library'][] = 'educational_programs_field/educational_programs_field';
}

/**
 * Implements hook_theme().
 */

function educational_programs_field_theme($existing, $type, $theme, $path)
{
  return [
    'educational_programs_field_default' => [
      'variables' => [
        'program' => [],
        'children' => [],
      ],
    ],
    'educational_programs_field_children' => [
      'variables' => [
        'subprograms' => [],
      ],
    ],
  ];
}
