<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function program_offering_blocks_preprocess_block(&$variables)
{
  // Include the program_offering_blocks css file for the block
  if (substr($variables['plugin_id'], 0, 23) == 'program_offering_blocks') {
    $variables['#attached']['library'][] = 'program_offering_blocks/program_offering_blocks_block';
    $variables['attributes']['class'][] = 'program_offering_blocks';
  }
}
