<?php

use Drupal\node\Entity\Node;

/**
* Implements hook_form_alter().
*/

function protect_nodes_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //Drupal::logger('protect_nodes')->info('In hook_form_alter: ' . $form_id);

  //if ($form_id == 'node_staff_profile_delete_form') {
  if (strpos($form_id, 'node') !== false && strpos($form_id, 'delete_form') !== false && $form_id != "node_type_delete_form") {

  $node = Node::load($form_state->getFormObject()->getEntity()->id());
  //Drupal::logger('protect_nodes')->info(json_encode($form['actions']));

  $results = '<ul>';
  $results .= '<li>' . $form_id . '</li>';
  $results .= '<li>' . $node->id() . '</li>';
  $results .= '<li>' . $node->getTitle() . '</li>';
  $results .= '<li>' . Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node->id()) . '</li>';
  $results .= '<li>' . $node->getType() . '</li>';
  $results .= '</ul>';

    $form['protect_nodes'] = array(
      '#markup' => $results,
      '#weight' => -10,
    );

    $form['actions']['cancel']['#title'] = t('Go back');
    //$form['actions']['Cancel']['#value'] = t('Go back');
    //$form['cancel']['#value'] = t('Go back');
    unset($form['description']);
    unset($form['actions']['submit']);
  }
}


