<?php

use \Drupal\node\Entity\Node;
use \Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_rebuild().
 */

function programs_rebuild()
{
  programs_getprograms();
}

/**
 * Implements hook_cron().
 */

function programs_cron()
{
  programs_getprograms();
}


function programs_getprograms()
{

  // Get the events feed, if it's empty, wait 1 second and try again
  $raw = file_get_contents('https://datastore.exnet.iastate.edu/mydata/EducationalPrograms.json');

  if ($raw === false || strlen($raw) < 100000) {
    sleep(1);
    Drupal::logger('events')->info('Empty feed: wait 1 second and try again');
    $raw = file_get_contents('https://datastore.exnet.iastate.edu/mydata/EducationalPrograms.json');
  }
  $programs = json_decode($raw, true);
  $programIds = [];
  $nodeIds = [];
  $min_programs = 100;
  if (!is_array($programs) || count($programs) < $min_programs) {
    Drupal::logger('programs')->info('Less than ' . $min_programs . ' programs, exiting');
    return;
  }

  // Get the taxonomy terms for Counties
  $counties = [];
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('counties_in_iowa');
  foreach ($terms as $term) {
    if ($term->name == 'Pottawattamie - East') $term->name = 'East Pottawattamie';
    if ($term->name == 'Pottawattamie - West') $term->name = 'West Pottawattamie';
    $counties[$term->name] = $term->tid;
  }

  $intended_audiences = [];
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('intended_audiences');
  foreach ($terms as $term) {
    $intended_audiences[$term->name] = $term->tid;
  }

  $program_areas = [];
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('program_areas');
  foreach ($terms as $term) {
    $program_areas[$term->name] = $term->tid;
  }

  // Get all existing nodes
  $nids = \Drupal::entityQuery('node')->condition('type', 'program')->execute();
  $nodes =  Node::loadMultiple($nids);
  foreach ($nodes as $node) {
    $nodeIds[] = $node->field_program_mydata_id->value;
  }

/*

  // Step through the events feed
  foreach ($events as $event) {

    $eventIds[] = $event['Id'];
    $mynode = null;
    $save = false;

    // Check for existing node for this event
    foreach ($nodes as $node) {
      if ($node->field_event_mydata_id->value == $event['Id']) {
        $mynode = $node;
        break;
      }
    }

    // Create node if one's not found
    if ($mynode == null) {
      $mynode = Node::create(array('type' => 'event', 'title' => html_entity_decode($event['Name_Placeholder__c']), 'field_event_mydata_id' => $event['Id'],));
      $save = true;
    }
    if ($event['Cancelled_Program__c'] && $mynode->isPublished()) {
      $mynode->setUnpublished();
      $save = true;
    }

    if (!$mynode->isPublished()) {
      $mynode->setPublished();
      $save = true;
    }

    // Handle the body
    $body = '';
    if (strlen($event['Program_Description__c']) > 0) {
      $body .= '<div>' . $event['Program_Description__c'] . '</div>' . PHP_EOL;
    }
    if (strlen($event['Planned_Program__r.Web_Description__c']) > 0) {
      $body .= '<div>' . $event['Planned_Program__r.Web_Description__c'] . '</div>' . PHP_EOL;
    }
    if ($mynode->body->value != $body) {
      $mynode->body->value = $body;
      $mynode->body->format = 'full_html';
      $save = true;
    }

    // Handle the text fields using an array and a loop
    $fields = [
      'field_event_contact_name' => 'Contact_Information_Name__c',
      'field_event_contact_email' => 'Contact_Information_Email__c',
      'field_event_contact_phone' => 'Contact_Information_Phone__c',
      'field_event_instructor_name' => 'Instructor_Information_Name__c',
      'field_event_instructor_email' => 'Instructor_Information_Email__c',
      'field_event_instructor_phone' => 'Instructor_Information_Phone__c',
      'field_event_location_site' => 'Event_Location_Site_Building__c',
      'field_event_location_street' => 'Event_Location_Street_Address__c',
      'field_event_location_city' => 'Event_Location__c',
      'field_event_location_state' => 'Program_State__c',
      'field_event_location_zip' => 'Event_Location_Zip_Code__c',
      'field_event_program_id' => 'Planned_Program__c',
      //'field_event_program_name' => '',
    ];
    foreach ($fields as $key => $value) {
      if ($mynode->get($key)->getString() != $event[$value]) {
        $mynode->set($key, $event[$value]);
        $save = true;
      }
    }

    $fields = [
      'field_event_program_url' => 'Planned_Program_Website__c',
      'field_event_url' => 'Program_Offering_Website__c',
      'field_event_registration_url' => 'Registration_Link__c',
    ];
    foreach ($fields as $key => $value) {
      if ($mynode->get($key)->uri != $event[$value]) {
        $mynode->set($key, ['uri' => $event[$value]]);
        $save = true;
      }
    }

    $fields = [
      'field_event_registration_opens' => 'Registration_Opens__c',
      'field_event_registration_deadlin' => 'Registration_Deadline__c',
      'field_event_next_start_date' => 'Next_Start_Date__c',
    ];
    foreach ($fields as $key => $value) {
      if ($mynode->get($key)->getString() != str_replace('Z', '', $event[$value])) {
        $mynode->set($key, str_replace('Z', '', $event[$value]));
        $save = true;
      }
    }

    // Handle Start/End Dates
    $sessions = event_get_dates($event);
    $count = 0;
    $existingStartDates = $mynode->get('field_event_start_dates')->getString();
    $existingEndDates = $mynode->get('field_event_end_dates')->getString();
    $newStartDates = implode(', ', $sessions[0]);
    $newEndDates = implode(', ', $sessions[1]);
    //if (count(explode(', ', $existingStartDates)) > 1) {
    if ($existingStartDates != $newStartDates) {
      $mynode->set('field_event_start_dates', $sessions[0]);
      $mynode->set('field_event_end_dates', $sessions[1]);
      $save = true;
    }
    if ($existingEndDates != $newEndDates) {
      $mynode->set('field_event_end_dates', $sessions[1]);
      $save = true;
    }

    // Handle Account (Host County)
    $host = 0;
    $acctName = str_replace(' County Extension', '', $event['Account__c.Name']);
    if (array_key_exists($acctName, $counties)) {
      $host = $counties[$acctName];
    }
    if ($mynode->get('field_event_account')->getString() != $host) {
      $mynode->set('field_event_account', $host);
      $save = true;
    }

    // Handle Additional Counties
    $feed_counties = explode(';', $event['Additional_Counties__c']);
    $new_counties = [];
    foreach ($feed_counties as $county) {
      $county = str_replace(' County', '', $county);
      if (array_key_exists($county, $counties)) {
        $new_counties[] = $counties[$county];
      }
    }
    if ($mynode->get('field_event_additional_counties')->getString() != implode(', ', $new_counties)) {
      $mynode->set('field_event_additional_counties', $new_counties);
      $save = true;
    }

    // Handle Program Area
    $term = 0;
    if (!empty($event['PrimaryProgramUnit__c'])) {
      if (!array_key_exists($event['PrimaryProgramUnit__c'], $program_areas)) {
        $program_areas[$event['PrimaryProgramUnit__c']] = Term::create(['name' => $event['PrimaryProgramUnit__c'], 'vid' => 'program_areas'])->save();
      }
      $term = $program_areas[$event['PrimaryProgramUnit__c']];
    }
    if ($mynode->get('field_event_program_area')->getString() != $term) {
      $mynode->set('field_event_program_area', $term);
      $save = true;
    }

    // Handle Intended Audiences
    $terms = [];
      if (!empty($event['Audiences__c'])) {
    foreach (explode(';', $event['Audiences__c']) as $audience) {
        if (!array_key_exists($audience, $intended_audiences)) {
          $intended_audiences[$audience] = Term::create(['name' => $audience, 'vid' => 'intended_audiences'])->save();
        }
        $terms[] = $intended_audiences[$audience];
      }
    }
    if ($mynode->get('field_event_audiences')->getString() != implode(', ', $terms)) {
      $mynode->set('field_event_audiences', $terms);
      $save = true;
    }

    // Only save if there has been a changed, this saves a ton of time
    if ($save) {
      $mynode->save();
    }
  }

  // Find and unpublish deleted events
  $deleted = array_diff($nodeIds, $eventIds);
  foreach ($nodes as $node) {
    if (in_array($node->field_event_mydata_id->value, $deleted) && $node->isPublished()) {
      $node->setUnpublished()->save();
      //$node->delete();
    }
  }
*/
}

