<?php
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\user\Entity\User;
use \Drupal\Core\Url;

function staff_profile_reed_uninstall() {
  \Drupal::configFactory()->getEditable('views.view.regional_director_county')->delete();
}

//Issue may be solved in 9.2 https://www.drupal.org/project/drupal/issues/2570593
function staff_profile_reed_entity_type_alter(array &$entity_types) {
  $entity_types['node']->setFormClass('add_cty_author', 'Drupal\staff_profile_reed\Forms\StaffProfileReedAddCtyAuthorConfirmForm');
  $entity_types['node']->setFormClass('remove_cty_author', 'Drupal\staff_profile_reed\Forms\StaffProfileReedRemoveCtyAuthorForm');
}

function staff_profile_reed_entity_operation_alter(array &$operations, EntityInterface $entity) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == "staff_profile_reed.regional_director_panel" && in_array($entity->bundle(), ['staff_profile'])) {
    $view = views_get_current_view();
    $roles = \Drupal::currentUser()->getRoles();
    if (in_array('regional_director', $roles)) {
      $operations = [];
      $operations['remove_cty_author'] = array(
        'title' => t('Remove County Author'),
        'weight' => -10,
        'url' => Url::fromRoute("entity.staff_profile_reed.remove_cty_author_form", array(
              'node' => $entity->id(),
              'cty' => $view->args[0],//County to remove, rewritten later
              'destination' => Url::fromRoute("staff_profile_reed.regional_director_panel")->toString()
            )
          ),
      );
    }
  }
}

function staff_profile_reed_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode']
  );

  switch ($key) {
    //Adding users
    case 'request_staff_profile_editor_training_profile':
      //Sent to user that had staff_profile added
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Web Editor Training Requested', $options);
      $message['body'][] = t('You have been added to the @county county web editors.' . ($params['needstraining'] ? " Web Editor training has been requested for you to complete." : " No additional action is needed."), array('@county' => $params['county']));
      break;
    case 'request_staff_profile_editor_training_reg_director':
      //Sent to regional director that added staff_profile to county
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('You have added: @netid to @county web editors', array('@netid' => $params['netid'], '@county' => $params['county']), $options);
      $message['body'][] = t('You have added @netid to the @county county web editors. Please ensure you completed this action.' . ($params['needstraining'] ? " Training has been requested for this user." : " This user meets the training requrements."), array('@netid' => $params['netid'], '@county' => $params['county']));
      break;
    case 'request_staff_profile_editor_training_extweb':
      //Sent to extweb to notify that training was requested
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@director has added: @title to @county web editors', array('@netid' => $params['netid'], '@county' => $params['county'], '@director' => $params['reg_director']), $options);
      $message['body'][] = t('@director has added @netid to the @county county web editors. ' . ($params['needstraining'] ? " Training is been requested for this user." : " This user has the required Web Editor training"), array('@netid' => $params['netid'], '@county' => $params['county'], '@director' => $params['reg_director']));
      break;

    //Removing users
    case 'remove_staff_profile_editor_cty_reg_director':
      //Sent to regional director as record that they removed staff_profile from one of their counties
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('You have removed: @netid from @county web editors', array('@netid' => $params['netid'], '@county' => $params['county']), $options);
      $message['body'][] = t('You have removed @netid from @county county web editors. Please ensure you completed this action.', array('@netid' => $params['netid'], '@county' => $params['county']));
      break;
    case 'remove_staff_profile_editor_cty_extweb':
      //Sent to extweb to notify that staff_profile was removed from county
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@director has removed: @title from @county web editors', array('@netid' => $params['netid'], '@county' => $params['county'], '@director' => $params['reg_director']), $options);
      $message['body'][] = t('You have been added to the @county county web editors', array('@county' => $params['county']));
      break;
  }
}
