<?php
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\user\Entity\User;
use \Drupal\Core\Url;

function staff_profile_reed_uninstall() {
  \Drupal::configFactory()->getEditable('views.view.regional_director_county')->delete();
}

function staff_profile_reed_entity_operation_alter(array &$operations, EntityInterface $entity) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == "staff_profile_reed.county_web_editors" && in_array($entity->bundle(), ['staff_profile'])) {
    $view = views_get_current_view();
    $roles = \Drupal::currentUser()->getRoles();
    if (in_array('regional_director', $roles)) {
      $operations = [];
      $operations['remove_cty_editor'] = array(
        'title' => t('Remove County Editor'),
        'weight' => -10,
        'url' => Url::fromRoute("entity.staff_profile_reed.remove_cty_editor_form", array(
              'node' => $entity->id(),
              'cty' => $view->args[0],//County to remove, rewritten later
              'destination' => Url::fromRoute("staff_profile_reed.county_web_editors")->toString()
          )
        ),
      );
    }
  }
}

function staff_profile_reed_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode']
  );

  switch ($key) {
    //Adding users
    case 'request_staff_profile_editor_training_profile':
      //Sent to user that had staff_profile added
      $message['from'] = \Drupal::config('system.site')->get('mail');
      if ($params['needstraining']) {
        $message['subject'] = t('Web Editor Training Requested', $options);
        $message['body'][] = t('Notice: @director requested that you be given content editor access for @county county. To gain access, you must take the Content Editor Training at https://moodle.extension.iastate.edu/course/view.php?id=211. Please note that access is granted automatically, and there is no need to email or inform anyone once you have completed the training. Be patient, as it may take up to 24 hours for access to be granted after completing the training. Please submit all website related support requests through the ticketing system at https://isuextweb.atlassian.net/servicedesk/customer/portals.', array('@county' => trim($params['county'])));
      } else {
        $message['subject'] = t('Web Editor Access Given', $options);
        $message['body'][] = t('Notice: You have been added as a @county county content editor. Login capabilities may take up to 24 hours after this notification.  No additional action is needed. Please submit all website related support requests through the ticketing system at https://isuextweb.atlassian.net/servicedesk/customer/portals.', array('@county' => trim($params['county'])));
      }
      break;
    case 'request_staff_profile_editor_training_reg_director':
      //Sent to regional director that added staff_profile to county
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('You have added: "@name" [@netid] as a @county county content editor.', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county'])), $options);
      $message['body'][] = t('Notice: You have added "@name" [@netid] as a @county county content editor.' . ($params['needstraining'] ? " Training has been requested for this user." : " This user meets the training requrements."), array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county'])));
      break;
    case 'request_staff_profile_editor_training_extweb':
      //Sent to extweb to notify that training was requested
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@director has added: "@name" [@netid] as a @county county content editor', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county']), '@director' => $params['reg_director']), $options);
      $message['body'][] = t('Notice: User @director has added "@name" [@netid] as a @county county content editor. ' . ($params['needstraining'] ? "Training has been requested for this user." : "This user has the required Web Editor training"), array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county']), '@director' => $params['reg_director']));
      break;

    //Removing users
    case 'remove_staff_profile_editor_cty_reg_director':
      //Sent to regional director as record that they removed staff_profile from one of their counties
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('You have removed: "@name" [@netid] as a @county county content editor', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county'])), $options);
      $message['body'][] = t('Notice: You have removed "@name" [@netid] as a @county county content editor.', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county'])));
      break;
    case 'remove_staff_profile_editor_cty_extweb':
      //Sent to extweb to notify that staff_profile was removed from county
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@director has removed: "@name" [@netid] as a @county county content editor', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county']), '@director' => $params['reg_director']), $options);
      $message['body'][] = t('Notice: User @director has removed "@name" [@netid] from @county county content editor', array('@name' => $params['name'], '@netid' => $params['netid'], '@county' => trim($params['county']), '@director' => $params['reg_director']));
      break;
  }
}
