<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function staff_contact_field_preprocess_block(&$variables)
{
  // Include the program_offering_blocks css file for the block
  if (substr($variables['plugin_id'], 0, 23) == 'staff_contact_field') {
    $variables['#attached']['library'][] = 'staff_contact_field/staff_contact_field';
    $variables['attributes']['class'][] = 'council_members';
  }
}
