<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function social_red_preprocess_block(&$variables)
{
  // Include the program_offering_blocks css file for the block
  if (substr($variables['plugin_id'], 0, 23) == 'social_red') {
    $variables['#attached']['library'][] = 'social_red/social_red';
    $variables['attributes']['class'][] = 'social_red';
  }
}

/**
* Implementation of hook_theme()
*/
function social_red_theme($existing, $type, $theme, $path) {
  return [
    'block__social_media_red_bar' => [
      'variables' => [
        'attributes' => array(),
      ],
    ],
  ];
}
