<?php

/*
 * Implements hook_ENTITY_TYPE_update()
 */

use Drupal\contact\Entity\Message;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_entity_presave().
 */

function county_impact_report_node_presave(Drupal\Core\Entity\EntityInterface $entity)
{
  $userId = \Drupal::currentUser()->id();
  if ($entity->getType() == 'county_impact_report') {
    $entity->setOwnerId($userId);
  }
}

function county_impact_report_content_update(Drupal\Core\Entity\EntityInterface $entity)
{
  // Clear cache if BlockContent is of type
  if ($entity->bundle() == 'county_impact_remport') {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

function county_impact_report_theme_suggestions_block_alter(&$suggestions, $variables)
{
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }
}

function county_impact_report_preprocess_block(&$variables)
{
  $variables['#attached']['library'][] = 'county_impact_report/county_impact_report';
}

/**
 * Implements hook_theme().
 */
function county_impact_report_theme($existing, $type, $theme, $path)
{
  return [
    'paragraph__county_impact_story' => [
      'variables' => [
        'direct_contacts' => 0,
        'volunteer_hours' => 0,
        'youth' => 0,
        'partners' => 0,
        'certifications' => 0,
        'volunteer_value' => 0,
      ],
      'template' => 'paragraph--county-impact-story',
      'base hook' => 'paragraph',
    ],
    'page__type__county_impact_report__canonical' => [
      'variables' => [
        'direct_contacts' => 0,
        'volunteer_hours' => 0,
        'youth' => 0,
        'partners' => 0,
        'certifications' => 0,
        'volunteer_value' => 0,
      ],
      'template' => 'page--type--county-impact-report--canonical',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */

function county_impact_report_preprocess_paragraph__county_impact_story(&$variables)
{
  $site_name = str_replace(' County', '', \Drupal::config('system.site')->get('name'));
  $data = county_impact_report_impact_data();

  $variables['direct_contacts'] = number_format($data[$site_name][0]);
  $variables['volunteer_hours'] = number_format($data[$site_name][1]);
  $variables['youth'] = number_format($data[$site_name][2]);
  $variables['partners'] = number_format($data[$site_name][3]);
  $variables['certifications'] = number_format($data[$site_name][4]);
  $variables['volunteer_value'] = number_format($data[$site_name][5]);
}

/**
 * Implements hook_preprocess_HOOK().
 */

function county_impact_report_preprocess_page__type__county_impact_report__canonical(&$variables)
{
  $site_name = str_replace(' County', '', \Drupal::config('system.site')->get('name'));
  $data = county_impact_report_impact_data();

  $variables['direct_contacts'] = number_format($data[$site_name][0]);
  $variables['volunteer_hours'] = number_format($data[$site_name][1]);
  $variables['youth'] = number_format($data[$site_name][2]);
  $variables['partners'] = number_format($data[$site_name][3]);
  $variables['certifications'] = number_format($data[$site_name][4]);
  $variables['volunteer_value'] = number_format($data[$site_name][5]);
}

function county_impact_report_impact_data()
{
  return [
    'Adair' => [4720, 981, 640, 12, 404, 28331.28,],
    'Adams' => [1958, 257, 241, 16, 121, 7422.16,],
    'Allamakee' => [7093, 815.25, 730, 31, 478, 23544.42,],
    'Appanoose' => [4806, 1494, 678, 24, 281, 43146.72,],
    'Audubon' => [3842, 711.5, 423, 11, 242, 20548.12,],
    'Benton' => [8460, 1758.45, 1809, 26, 918, 50784.04,],
    'Black Hawk' => [19909, 5697.44, 5579, 113, 3829, 164542.07,],
    'Boone' => [10205, 2907.4, 1918, 42, 877, 83965.71,],
    'Bremer' => [11787, 2099.25, 1720, 55, 787, 60626.34,],
    'Buchanan' => [9155, 1614.72, 1817, 27, 785, 46633.11,],
    'Buena Vista' => [4084, 1663.5, 735, 29, 554, 48041.88,],
    'Butler' => [4363, 1368.5, 511, 29, 416, 39522.28,],
    'Calhoun' => [4398, 876, 604, 17, 264, 25298.88,],
    'Carroll' => [11139, 1366, 4195, 28, 887, 39450.08,],
    'Cass' => [7047, 1574.9, 1056, 20, 596, 45483.11,],
    'Cedar' => [6768, 2867.5, 1859, 26, 679, 82813.40,],
    'Cerro Gordo' => [11938, 1344.2, 5115, 19, 1614, 38820.50,],
    'Cherokee' => [3683, 715.45, 499, 16, 527, 20662.20,],
    'Chickasaw' => [3268, 913, 431, 8, 529, 26367.44,],
    'Clarke' => [3180, 1065.95, 243, 16, 318, 30784.64,],
    'Clay' => [8288, 1029.5, 3049, 22, 722, 29731.96,],
    'Clayton' => [9416, 8920.5, 1226, 21, 659, 257624.04,],
    'Clinton' => [8466, 4852.05, 578, 21, 1038, 140127.20,],
    'Crawford' => [4644, 1443, 346, 11, 503, 41673.84,],
    'Dallas' => [17635, 9290.3, 1152, 36, 3483, 268303.86,],
    'Davis' => [3738, 2878.25, 709, 3, 188, 83123.86,],
    'Decatur' => [2816, 835, 229, 6, 216, 24114.80,],
    'Delaware' => [16671, 5878.75, 2652, 23, 681, 169778.30,],
    'Des Moines' => [10230, 3142.54, 436, 16, 1830, 90756.56,],
    'Dickinson' => [8636, 689.75, 2607, 41, 510, 19919.98,],
    'Dubuque' => [36476, 7915.05, 7789, 137, 3661, 228586.64,],
    'East Pottawattamie' => [5540, 89.25, 489, 28, 116, 2577.54,],
    'Emmet' => [3442, 328, 200, 8, 276, 9472.64,],
    'Fayette' => [11141, 2326.8, 1031, 71, 616, 67197.98,],
    'Floyd' => [9301, 1354, 1240, 25, 405, 39103.52,],
    'Franklin' => [5399, 99.9, 777, 19, 376, 2885.11,],
    'Fremont' => [4220, 399.5, 330, 22, 178, 11537.56,],
    'Greene' => [5191, 1500, 341, 36, 358, 43320.00,],
    'Grundy' => [5520, 3829, 874, 38, 540, 110581.52,],
    'Guthrie' => [4838, 965, 487, 8, 369, 27869.20,],
    'Hamilton' => [6962, 1478.18, 750, 28, 428, 42689.84,],
    'Hancock' => [6964, 551.5, 613, 20, 392, 15927.32,],
    'Hardin' => [4074, 77, 335, 8, 376, 2223.76,],
    'Harrison' => [4571, 1078.7, 493, 30, 468, 31152.86,],
    'Henry' => [10724, 1354.2, 3305, 45, 553, 39109.30,],
    'Howard' => [5493, 1019, 601, 9, 538, 29428.72,],
    'Humboldt' => [4304, 1052.25, 672, 4, 261, 30388.98,],
    'Ida' => [2804, 730, 199, 6, 267, 21082.40,],
    'Iowa' => [23136, 2711.65, 6420, 9, 12531, 78312.45,],
    'Jackson' => [7559, 6977.5, 817, 40, 574, 201510.20,],
    'Jasper' => [9567, 11147.66, 779, 26, 1213, 321944.42,],
    'Jefferson' => [5851, 3845, 942, 28, 403, 111043.60,],
    'Johnson' => [15809, 9591.35, 1933, 36, 5575, 276998.19,],
    'Jones' => [6784, 3954.2, 637, 3, 780, 114197.30,],
    'Keokuk' => [7958, 1837.55, 579, 12, 251, 53068.44,],
    'Kossuth' => [5414, 1217.4, 740, 23, 426, 35158.51,],
    'Lee' => [9662, 75.67, 960, 49, 1068, 2185.35,],
    'Linn' => [25421, 16194.71, 4791, 58, 7273, 467703.22,],
    'Louisa' => [5006, 691.95, 1591, 20, 412, 19983.52,],
    'Lucas' => [3009, 1197, 430, 44, 274, 34569.36,],
    'Lyon' => [7424, 675.5, 768, 21, 559, 19508.44,],
    'Madison' => [6405, 2893, 1134, 30, 585, 83549.84,],
    'Mahaska' => [7414, 2792, 551, 27, 614, 80632.96,],
    'Marion' => [7950, 1641.15, 972, 22, 1069, 47396.41,],
    'Marshall' => [6634, 1139.35, 1191, 27, 1130, 32904.43,],
    'Mills' => [4991, 1725.65, 1836, 26, 300, 49836.77,],
    'Mitchell' => [6354, 944.5, 569, 20, 395, 27277.16,],
    'Monona' => [3682, 894.5, 1324, 11, 146, 25833.16,],
    'Monroe' => [4116, 1480.5, 399, 31, 86, 42756.84,],
    'Montgomery' => [3491, 504, 419, 23, 424, 14555.52,],
    'Muscatine' => [6194, 1840, 937, 38, 1176, 53139.20,],
    'O\'Brien' => [6041, 1290.75, 1257, 42, 616, 37276.86,],
    'Osceola' => [2899, 957, 396, 22, 294, 27638.16,],
    'Page' => [6994, 1868, 1063, 14, 743, 53947.84,],
    'Palo Alto' => [5711, 551.5, 367, 39, 292, 15927.32,],
    'Plymouth' => [9761, 5728.25, 782, 13, 917, 165431.86,],
    'Pocahontas' => [3097, 647, 393, 23, 200, 18685.36,],
    'Polk' => [52854, 16851.15, 3034, 111, 18242, 486661.21,],
    'Poweshiek' => [4714, 1101.15, 323, 13, 736, 31801.21,],
    'Ringgold' => [2235, 245, 204, 18, 202, 7075.60,],
    'Sac' => [5364, 929.05, 401, 8, 336, 26830.96,],
    'Scott' => [12327, 4930.95, 1559, 22, 4309, 142405.84,],
    'Shelby' => [4796, 1320.2, 664, 27, 469, 38127.38,],
    'Sioux' => [9088, 865.56, 963, 47, 1172, 24997.37,],
    'Story' => [19817, 11060.4, 3052, 73, 2961, 319424.35,],
    'Tama' => [7638, 1877.75, 2105, 55, 679, 54229.42,],
    'Taylor' => [2180, 70, 116, 13, 226, 2021.60,],
    'Union' => [4035, 702.5, 628, 5, 493, 20288.20,],
    'Van Buren' => [2355, 2200, 314, 26, 151, 63536.00,],
    'Wapello' => [8975, 1899.25, 544, 19, 822, 54850.34,],
    'Warren' => [12081, 5244.77, 1185, 15, 2062, 151468.96,],
    'Washington' => [18188, 7939.75, 2874, 36, 747, 229299.98,],
    'Wayne' => [2345, 824, 855, 14, 120, 23797.12,],
    'Webster' => [6825, 1797.05, 603, 22, 1074, 51898.80,],
    'West Pottawattamie' => [12790, 2684.25, 397, 32, 1549, 77521.14,],
    'Winnebago' => [3142, 496.5, 492, 53, 327, 14338.92,],
    'Winneshiek' => [13045, 2831.95, 1405, 87, 737, 81786.72,],
    'Woodbury' => [17431, 4122.4, 5232, 64, 3319, 119054.91,],
    'Worth' => [3466, 5, 425, 4, 171, 144.40,],
    'Wright' => [3685, 834, 526, 8, 366, 24085.92,],
  ];
}

/**
 * Implements hook_form_alter().
 */

function county_impact_report_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == 'node_county_impact_report_edit_form') {

    $form['actions']['save_review'] = array(
      '#type' => 'submit',
      '#value' => 'Save & Submit for Review',
      '#name' => 'op',
      //'#submit' => ['county_impact_report_form_submit'], /* NEED this */
      '#submit' => array_merge(
        $form['actions']['submit']['#submit'],
        ['county_impact_report_form_submit']
      ),
      '#weight' => 10
    );
  }
}

// Handle the form submission
function county_impact_report_form_submit($form, FormStateInterface $form_state)
{
  $node = $form_state->getFormObject()->getEntity();

  $params = county_impact_report_build_params($node);
  $params['key'] = 'county_impact_report_to_reed';
  $params['to'] = $params['reed'];
  $params['reply'] = 'Content Editor <' . $params['content_editor'] . '>';
  $params['subject'] = 'Review - ' . $params['title'];
  county_impact_report_send_mail($params);

  $params['subject'] = 'Approval Link for ' . $params['title'];
  $params['message'] = 'The approval link for ' . $params['title'] . ' is ' . \Drupal::request()->getSchemeAndHttpHost() . \Drupal::request()->getBaseUrl() . '/regional_director_approval '
    . 'Only use this link for the FINAL approval';
  $params['reply'] = 'Extension Web <extensionweb@iastate.edu>';

  county_impact_report_send_mail($params);

  \Drupal::messenger()->addStatus('Saved, and Submitted to Regional Director for Review!');
}

/**
 * Implements hook_mail().
 */

function county_impact_report_mail($key, &$message, $params)
{
  //$from = 'Extension Web <extensionweb@iastate.edu>';

  //$message['from'] = $from;
  //$message['headers']['From'] = $from;
  //$message['headers']['Sender'] = $from;
  $message['body'][] = $params['message'];
  $message['subject'] = $params['subject'];
  $message['headers']['reply-To'] = $params['reply'];
}

function county_impact_report_get_emails($nodes, string $title, string $defaultAddress)
{
  $address = $defaultAddress;
  foreach ($nodes as $node) {
    if (str_contains(strtolower($node->field_staff_profile_job_title->value), strtolower($title))) {
      $address = $node->field_staff_profile_email->value;
      break;
    }
  }
  return $address;
}

function county_impact_report_build_params($node)
{
  $nids = \Drupal::entityQuery('node')->accessCheck(true)->condition('type', 'staff_profile')->condition('status', 1)->execute();
  $staffNodes =  \Drupal\node\Entity\Node::loadMultiple($nids);
  $params = [];
  $params['title'] = $node->getTitle();
  $params['content_editor'] = $node->getOwner()->getEmail();
  $params['reed'] = county_impact_report_get_emails($staffNodes, 'Assistant Director County Services', 'andwelch@iastate.edu');
  $params['advancement_specialist'] = county_impact_report_get_emails($staffNodes, 'Marketing Specialist', 'jbrimey@iastate.edu');
  $params['module'] = 'county_impact_report';
  $params['langcode'] = 'en';
  $params['send'] = true;
  $params['reply'] = NULL;

  $paragraphs = $node->get('field_impact_story');
  $message = '<br>';
  $message .= $params['title'];
  $message .= '<br>';
  $message .= 'Last edited by: ' . $params['content_editor'];
  $message .= '<br>';
  $message .= '<p>';
  $message .= '*******BEGIN OUTPUT OF DRAFT CONTENT*******';
  $message .= '</p>';
  foreach ($paragraphs as $paragraph) {
    $values = Paragraph::load($paragraph->target_id);
    $image = Media::load($values->field_county_impact_story_image->getValue()[0]['target_id']);
    $file = File::load($image->field_media_image->target_id);

    $message .= '<br>';
    $message .= '<br>';
    //$message .= '<strong>' . $values->field_county_impact_story_title->value . '</strong>';
    $message .= PHP_EOL;
    $message .= $values->field_county_impact_story_title->value;
    $message .= PHP_EOL;
    $message .= '<br>';
    $message .= $values->field_county_impact_story_body->getValue()[0]['value'];
    if ($file) {
      //$img = '<img src="' . \Drupal::request()->getSchemeAndHttpHost() . \Drupal::request()->getBaseUrl() . '/files/' . str_replace('public://', '', $file->getFileUri()) . '" alt="' . $image->toArray()['field_media_image'][0]['alt'] . '" style="max-width: 300px;" />';
      //$message .= $img;
      //$message .= '<br>';
      $message .= str_replace(' ', '%20', \Drupal::request()->getSchemeAndHttpHost() . \Drupal::request()->getBaseUrl() . '/files/' . str_replace('public://', '', $file->getFileUri()));
    }
    $message .= '<br>';
    $message .= '-----------------';
    $message .= '<br>';
    $message .= PHP_EOL;
  }

  $params['message'] = $message;

  return $params;
}

function county_impact_report_send_mail($params)
{
  try {
    $mailManager = \Drupal::service('plugin.manager.mail');

    $result = $mailManager->mail($params['module'], $params['key'], $params['to'], $params['langcode'], $params, $params['NULL'], $params['send']);
    if ($result['result'] != true) {
      $errorMessage = t('There was a problem sending your email notification to @email.', array('@email' => $params['to']));
      \Drupal::messenger()->addError($errorMessage);
      \Drupal::logger('county_impact_report')->error($errorMessage);
      return;
    }

    $successMessage = t('An email notification has been sent to @email ', array('@email' => $params['to']));
    \Drupal::messenger()->addStatus($successMessage);
    \Drupal::logger('county_impact_report')->notice($successMessage);
  } catch (Exception $e) {
    \Drupal::messenger()->addStatus($e->getMessage());
  }
}
