<?php

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_menu_local_tasks_alter().
 * Add tab with custom title and link only to pages of a selected content type
 */
function layout_content_type_menu_local_tasks_alter(&$data, $route_name) {
  if (is_array($data['tabs'][0]['field_ui.fields:display_overview_node']['#link'])) {
	$thing = $data['tabs'][0]['field_ui.fields:display_overview_node']['#link']['url']->getRouteParameters();

	if ($thing['node_type'] == 'layoutCT') {
	  $data['tabs'][0]['layout_content_type.manage_layout'] = array(
		'#theme' => 'menu_local_task',
		'#link' => array(
		  'title' => 'Manage Layout',
		  'url' => \Drupal\Core\Url::fromUri('internal:/admin/structure/types/manage/layoutCT/display/default/layout'),
		  'localized_options' => array(),
		),
		'#weight' => 4,
	  );

	  $data['tabs'][0]['field_ui.fields:display_overview_node']['#access'] = FALSE;
	}
  }

}

/**
 * Implements hook_menu_links_discovered_alter().
 * Modifies existing 'Manage display' to now host layout_builder
 */
function layout_content_type_menu_links_discovered_alter(&$links) {
  $links['admin_toolbar_tools.extra_links:entity.entity_view_display.node.default.layoutCT']['title'] = 'Manage layout';
  $links['admin_toolbar_tools.extra_links:entity.entity_view_display.node.default.layoutCT']['url'] = "internal:/admin/structure/types/manage/layoutCT/display/default/layout";
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Hides permissions layout_restriction and layout_builder options to users
 */
/*
function layout_content_type_form_entity_view_display_edit_form_alter(&$form, &$form_state, $form_id) {
  hide($form['modes']);
  hide($form['layout']);
  hide($form['actions']);
}
*/

