<?php

/*
 * Implements hook_ENTITY_TYPE_update()
 */
function flip_cards_block_content_update(Drupal\Core\Entity\EntityInterface $entity) {
	// Clear cache if BlockContent is of type 'content_card'
  if ($entity->bundle() == 'flip_cards') {
	  \Drupal::service('cache.render')->invalidateAll();
  }
}

function flip_cards_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }
}

function flip_cards_preprocess_block(&$variables) {
  //Layout builder flipcards have $variables['plugin_id'], custom block library uses uuid, need to check bundle for them
  if ($variables['plugin_id'] == 'inline_block:flip_cards' || ($variables ?? 'elements' ?? 'content' ?? '#block_content'->bundle() == 'flip_cards')) {
    $variables['#attached']['library'][] = 'flip_cards/flip_cards';
    $variables['attributes']['class'][] = 'flip_cards';
  }
}
