<?php

use \Drupal\taxonomy\Entity\Vocabulary;

/**
* Implements hook_install().
*/

function isueo_categories_topics_install() {
  isueo_categories_topics_build_taxonomy();
}

/**
 * Implements hook_uninstall().
 */

function isueo_categories_topics_uninstall()
{
  // Remove the taxonomy this module created
  $taxonomy = Vocabulary::load('categories_topics');
  if ($taxonomy) {
    $taxonomy->delete();
  }
}
