<?php

use \Drupal\isueo_helpers\ISUEOHelpers\Typesense;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */

function isueo_ts_indexer_node_delete(Drupal\Core\Entity\EntityInterface $entity)
{
  try {
    $config = Drupal::config('isueo_ts_indexer.settings');
    $client = Typesense::getClient($config->get('api_key'));

    $contentTypes = $config->get('content_types');

    if (in_array($entity->bundle(), $contentTypes)) {
      $client->collections[$config->get('collection')]->documents[$config->get('site_name') . ':' . $entity->id()]->delete();
    }
  } catch (Exception $e) {
    Drupal::logger('isueo_ts_indexer')->error('Deleting a node: ' . $e->getMessage());
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */

function isueo_ts_indexer_node_update(Drupal\Core\Entity\EntityInterface $entity)
{
  $config = Drupal::config('isueo_ts_indexer.settings');

  $contentTypes = $config->get('content_types');

  if (in_array($entity->bundle(), $contentTypes)) {
    isueo_ts_indexer_index_node($entity->id(), $config->get('api_key'), $config->get('collection'), $config->get('site_name'));
    //isueo_ts_indexer_index_node($entity), $config->get('api_key'), $config->get('collection'), $config->get('site_name'));
  }
}

function isueo_ts_indexer_index_node(int $nid, string $api_key, string $collection, string $site_name)
{
  try {
    $node = Drupal::entityTypeManager()->getStorage('node')->load($nid);

    if ($node) {
      $client = Typesense::getClient($api_key);
      $record = [
        'id' => $site_name . ':' . $nid,
        'title' => $node->getTitle(),
        'site_name' => $site_name,
        'url' => $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid),
        'content_type' => $node->bundle(),
      ];
      $client->collections[$collection]->documents->upsert($record);
    }
  } catch (Exception $e) {
    Drupal::logger('isueo_ts_indexer')->error('Saving a node: ' . $e->getMessage());
  }
}

function isueo_ts_indexer_index_all_nodes()
{
  try {
    $config = Drupal::config('isueo_ts_indexer.settings');
    $contentTypes = array_values($config->get('content_types'));

    $client = Typesense::getClient($config->get('api_key'));
    $client->collections[$config->get('collection')]->documents->delete(['filter_by' => 'site_name:=' . $config->get('site_name'),]);

    foreach ($contentTypes as $type) {
      $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['type' => $type]);
      foreach ($nodes as $node) {
        isueo_ts_indexer_index_node($node->id(), $config->get('api_key'), $config->get('collection'), $config->get('site_name'));
      }
    }
  } catch (Exception $e) {
    Drupal::logger('isueo_ts_indexer')->error('Indexing all nodes: ' . $e->getMessage());
  }
}
