<?php

/**
 * @file
 * Layout Builder Permissions functionality.
 */

use Drupal\layout_builder_perms\LayoutBuilderElement;

/**
 * Implements hook_PLUGIN_MANAGER_ID_alter().
 */
function layout_builder_perms_layout_builder_section_storage_alter(array &$definitions) {
  if (!empty($definitions['overrides'])) {
    // Override plugin class for Overrides section storage plugin.
    $definitions['overrides']->setClass('Drupal\layout_builder_perms\Plugin\SectionStorage\OverridesSectionStorage');
  }
}

/**
 * Implements hook_element_info_alter().
 */
function layout_builder_perms_element_info_alter(array &$info) {
  if (!empty($info['layout_builder'])) {
    $info['layout_builder']['#pre_render'][] = [LayoutBuilderElement::class, 'preRender'];
  }
}
