<?php

function links_block_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }
}

/**
 * Implements hook_preprocess_HOOK()
 */
function links_block_preprocess_block(&$variables)
{
    $variables['#attached']['library'][] = 'links_block/links_block';
  }
